version: '3.8'

services:
  # 1. 数据库服务
  db:
    image: mysql:8.0
    container_name: minimes_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: minimes_db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  # 2. 后端服务
  backend:
    build: ./src/backend
    container_name: minimes_backend
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./src/backend:/app  # 挂载代码，改代码后自动重启

volumes:
  db_data: